# -*- coding: utf-8 -*-
"""HomeWork9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kCuxkOvB8N4SlUEd1AmwJebkmYHPvxBg
"""

import pandas

"""Задача 40: Работать с файлом california_housing_train.csv, который находится в папке
sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)
"""

df = pandas.read_csv('sample_data/california_housing_train.csv')
round(df[df['population']<=500]['median_house_value'].mean())

"""Задача 42: Узнать какая максимальная households в зоне минимального значения population"""

df[df['population']==df['population'].min()]['households'].max()